extends: airbnb-base

env:
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2018
  sourceType: script

rules:
  'comma-dangle': ['error', 'never']
  'strict': ['error', 'global']
  'max-len': ['error', { code: 120, ignoreComments: true }]
  'semi': ['error', 'never']
  'no-trailing-spaces': ['error', { skipBlankLines: true }]
  'object-curly-newline': ['error', { consistent: true }]
  'function-paren-newline': ['error', 'consistent']
